apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: micro-apps
  namespace: argocd
spec:

  generators:
    - list:
        elements:
          - name: assistantservice
            namespace: hipster-backend
          - name: authservice
            namespace: hipster-backend
          - name: cartservice
            namespace: hipster-backend
          - name: checkoutservice
            namespace: hipster-backend
          - name: currencyservice
            namespace: hipster-backend
          - name: emailservice
            namespace: hipster-backend
          - name: frontend
            namespace: hipster-frontend  
          - name: paymentservice
            namespace: hipster-backend
          - name: productcatalogservice
            namespace: hipster-backend
          - name: recommendationservice
            namespace: hipster-backend
          - name: shippingservice
            namespace: hipster-backend


  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      annotations:
        # Wave 3 
        argocd.argoproj.io/sync-wave: "3"
        argocd-image-updater.argoproj.io/image-list: "app=yampss/hipstershop-{{name}}"
        argocd-image-updater.argoproj.io/app.update-strategy: semver
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/app.helm.image-name: "global.images.{{name}}.repository"
        argocd-image-updater.argoproj.io/app.helm.image-tag:  "global.images.{{name}}.tag"

      finalizers:
        - resources-finalizer.argocd.argoproj.io

    spec:
      project: hipstershop

      source:
        repoURL: https://github.com/HipsterShopp/hipstershop-helm-charts
        targetRevision: main
        path: "hipstershop-micro-apps/{{name}}"
        helm:
          valueFiles:
            - values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true
