global:
  namespaces:
    backend: hipster-backend

  images:
    assistantservice: "yampss/hipstershop-assistantservice:latest"   

  replicas:
    assistantservice: 1

  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

  ports:
    assistantservice: 8080

  resources:
    standard:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
