# ─────────────────────────────────────────────────────────────
#  assistantservice — prod overrides
# ─────────────────────────────────────────────────────────────
global:
  replicas:
    assistantservice: 1
  resources:
    standard:
      requests: { cpu: 100m, memory: 128Mi }
      limits:   { cpu: 200m, memory: 256Mi }
  images:
    assistantservice: "yampss/hipstershop-assistantservice:latest"
