
global:
  namespaces:
    backend: hipster-backend

  images:
    shippingservice: "yampss/hipstershop-shippingservice:latest"   

  replicas:
    shippingservice: 1

  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

  ports:
    shippingservice: 50051

  resources:
    standard:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
