

global:
  namespaces:
    backend:  hipster-backend
    database: hipster-database

  images:
    productcatalogservice: "yampss/hipstershop-productcatalogservice:latest"  

  replicas:
    productcatalogservice: 1

  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

  ports:
    productcatalogservice: 3550

  resources:
    standard:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  mongodb:
    users:
      catalog:
        database: catalog_db

