# ─────────────────────────────────────────────────────────────
#  productcatalogservice — dev overrides
# ─────────────────────────────────────────────────────────────
global:
  replicas:
    productcatalogservice: 1
  resources:
    standard:
      requests: { cpu: 50m, memory: 64Mi }
      limits:   { cpu: 100m, memory: 128Mi }
  images:
    productcatalogservice: "yampss/hipstershop-productcatalogservice:develop-latest"
