
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions-shippingservice-verifier
  namespace: hipster-backend
  labels:
    managed-by: gitops
    purpose: github-actions-oidc
    service: shippingservice
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]  
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list"]                      
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]                      

---


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-shippingservice-verifier
  namespace: hipster-backend
  labels:
    managed-by: gitops
    purpose: github-actions-oidc
    service: shippingservice
subjects:
  - kind: User
    name: "github:repo:HipsterShopp/hipstershop-shippingservice:ref:refs/heads/main"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: github-actions-shippingservice-verifier
  apiGroup: rbac.authorization.k8s.io
