

global:
  namespaces:
    backend:  hipster-backend
    frontend: hipster-frontend

  gateway:
    name:             hipstershop-gateway
    gatewayClassName: kgateway
    port:             80


  frontendServiceName: "frontend"

  ports:
    adservice:             9555
    authservice:           8081
    cartservice:           7070
    checkoutservice:       5050
    currencyservice:       7000
    emailservice:          8080
    frontend:              8080   
    frontendSvc:           80      
    paymentservice:        50051
    productcatalogservice: 3550
    recommendationservice: 8080
    shippingservice:       50051
    assistantservice:      8080
