global:
  replicas:
    adservice: 1

  resources:
    adservice:
      requests:
        cpu: 200m
        memory: 180Mi
      limits:
        cpu: 300m
        memory: 512Mi


  images:
    adservice: "ghcr.io/hipstershopp/hipstershop-adservice:adservice-v0.2.3"
