global:
  replicas:
    adservice: 1

  resources:
    adservice:
      requests:
        cpu: 100m
        memory: 90Mi
      limits:
        cpu: 200m
        memory: 256Mi

  images:
    adservice: "yampss/hipstershop-adservice:develop-latest"
