global:
  namespaces:
    backend: hipster-backend

  images:
    adservice:
      repository: clustersix0ps/hipstershop-adservice
      tag: latest   

  replicas:
    adservice: 1

  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

  ports:
    adservice: 9555

  resources:
    adservice:
      requests:
        cpu: 200m
        memory: 180Mi
      limits:
        cpu: 300m
        memory: 512Mi
