

global:
  namespaces:
    backend:  hipster-backend
    database: hipster-database

  images:
    paymentservice: "yampss/hipstershop-paymentservice:latest" 

  replicas:
    paymentservice: 1

  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

  ports:
    paymentservice: 50051

  resources:
    standard:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  mongodb:
    users:
      payment:
        database: payment_db
