# ─────────────────────────────────────────────────────────────
#  paymentservice — dev overrides
# ─────────────────────────────────────────────────────────────
global:
  replicas:
    paymentservice: 1
  resources:
    standard:
      requests: { cpu: 50m, memory: 64Mi }
      limits:   { cpu: 100m, memory: 128Mi }
  images:
    paymentservice: "yampss/hipstershop-paymentservice:develop-bb339e6c"
