# ─────────────────────────────────────────────────────────────
#  paymentservice — prod overrides
# ─────────────────────────────────────────────────────────────
global:
  replicas:
    paymentservice: 1
  resources:
    standard:
      requests: { cpu: 100m, memory: 128Mi }
      limits:   { cpu: 200m, memory: 256Mi }
  images:
    paymentservice: "yampss/hipstershop-paymentservice:latest"
