apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hipstershop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "HipsterShop microservices platform — all charts and infra"

  sourceRepos:
    - "https://github.com/HipsterShopp/hipstershop-helm-charts"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: hipster-backend
    - server: https://kubernetes.default.svc
      namespace: hipster-frontend
    - server: https://kubernetes.default.svc
      namespace: hipster-database
    - server: https://kubernetes.default.svc
      namespace: kube-system          
    - server: https://kubernetes.default.svc
      namespace: ""                   


  clusterResourceWhitelist:
    - group: "*"
      kind: "*"


  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  orphanedResources:
    warn: true
