# ─────────────────────────────────────────────────────────────
#  frontend — prod overrides
# ─────────────────────────────────────────────────────────────
global:
  replicas:
    frontend: 1
  hpa:
    frontend:
      minReplicas: 2
      maxReplicas: 8
  resources:
    standard:
      requests: { cpu: 100m, memory: 128Mi }
      limits:   { cpu: 300m, memory: 512Mi }
  images:
    frontend: "yampss/hipstershop-frontend:frontend-v1.0.4"
