# ─────────────────────────────────────────────────────────────
#  recommendationservice — dev overrides
# ─────────────────────────────────────────────────────────────
global:
  replicas:
    recommendationservice: 1
  resources:
    recommendation:
      requests: { cpu: 50m,  memory: 110Mi }
      limits:   { cpu: 100m, memory: 225Mi }
  images:
    recommendationservice: "yampss/hipstershop-recommendationservice:develop-8e896022"
