# ─────────────────────────────────────────────────────────────
#  recommendationservice — dev overrides
# ─────────────────────────────────────────────────────────────
global:
  replicas:
    recommendationservice: 1
  resources:
    recommendation:
      requests: { cpu: 50m,  memory: 110Mi }
      limits:   { cpu: 100m, memory: 225Mi }
  images:
    recommendationservice: "854929211842.dkr.ecr.us-east-1.amazonaws.com/hipstershop-recommendationservice:develop-ca47ce29"
