
global:
  replicas:
    emailservice: 1
  resources:
    standard:
      requests: { cpu: 50m, memory: 64Mi }
      limits:   { cpu: 100m, memory: 128Mi }
  images:
    emailservice: "yampss/hipstershop-emailservice:develop-latest"
