{{- $ns := .Values.global.namespaces -}}
{{- $ports := .Values.global.ports -}}
{{- $gw := .Values.global.gateway -}}

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ $ns.backend }}
  name: frontend-route
  labels:
    app: frontend
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gw.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /static/
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.global.frontendServiceName }}
          namespace: {{ $ns.frontend }}
          port: {{ $ports.frontendSvc }}
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /_healthz
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.global.frontendServiceName }}
          namespace: {{ $ns.frontend }}
          port: {{ $ports.frontendSvc }}
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /product
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.global.frontendServiceName }}
          namespace: {{ $ns.frontend }}
          port: {{ $ports.frontendSvc }}
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /cart
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.global.frontendServiceName }}
          namespace: {{ $ns.frontend }}
          port: {{ $ports.frontendSvc }}
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /setCurrency
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.global.frontendServiceName }}
          namespace: {{ $ns.frontend }}
          port: {{ $ports.frontendSvc }}
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /login
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.global.frontendServiceName }}
          namespace: {{ $ns.frontend }}
          port: {{ $ports.frontendSvc }}
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /signup
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.global.frontendServiceName }}
          namespace: {{ $ns.frontend }}
          port: {{ $ports.frontendSvc }}
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /logout
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.global.frontendServiceName }}
          namespace: {{ $ns.frontend }}
          port: {{ $ports.frontendSvc }}
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Values.global.frontendServiceName }}
          namespace: {{ $ns.frontend }}
          port: {{ $ports.frontendSvc }}
          weight: 1
---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ $ns.backend }}
  name: ad-route
  labels:
    app: adservice
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gw.name }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/ads
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /ads
      backendRefs:
        - group: ""
          kind: Service
          name: adservice
          port: {{ $ports.adservice }}
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ $ns.backend }}
  name: auth-route
  labels:
    app: authservice
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gw.name }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/auth/login
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /login
      backendRefs:
        - group: ""
          kind: Service
          name: authservice
          port: {{ $ports.authservice }}
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /api/auth/signup
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /signup
      backendRefs:
        - group: ""
          kind: Service
          name: authservice
          port: {{ $ports.authservice }}
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /api/auth/logout
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /logout
      backendRefs:
        - group: ""
          kind: Service
          name: authservice
          port: {{ $ports.authservice }}
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /api/auth/me
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /me
      backendRefs:
        - group: ""
          kind: Service
          name: authservice
          port: {{ $ports.authservice }}
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ $ns.backend }}
  name: cart-route
  labels:
    app: cartservice
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gw.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/cart
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /cart
      backendRefs:
        - group: ""
          kind: Service
          name: cartservice
          port: {{ $ports.cartservice }}
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ $ns.backend }}
  name: checkout-route
  labels:
    app: checkoutservice
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gw.name }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/checkout
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /checkout
      backendRefs:
        - group: ""
          kind: Service
          name: checkoutservice
          port: {{ $ports.checkoutservice }}
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ $ns.backend }}
  name: currency-route
  labels:
    app: currencyservice
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gw.name }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/currency/currencies
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /currencies
      backendRefs:
        - group: ""
          kind: Service
          name: currencyservice
          port: {{ $ports.currencyservice }}
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /api/currency/convert
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /convert
      backendRefs:
        - group: ""
          kind: Service
          name: currencyservice
          port: {{ $ports.currencyservice }}
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ $ns.backend }}
  name: email-route
  labels:
    app: emailservice
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gw.name }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/email/send-confirmation
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /send-confirmation
      backendRefs:
        - group: ""
          kind: Service
          name: emailservice
          port: {{ $ports.emailservice }}
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ $ns.backend }}
  name: payment-route
  labels:
    app: paymentservice
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gw.name }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/payment/charge
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /charge
      backendRefs:
        - group: ""
          kind: Service
          name: paymentservice
          port: {{ $ports.paymentservice }}
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ $ns.backend }}
  name: productcatalog-route
  labels:
    app: productcatalogservice
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gw.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/products/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /products/
      backendRefs:
        - group: ""
          kind: Service
          name: productcatalogservice
          port: {{ $ports.productcatalogservice }}
          weight: 1
    - matches:
        - path:
            type: Exact
            value: /api/products
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /products
      backendRefs:
        - group: ""
          kind: Service
          name: productcatalogservice
          port: {{ $ports.productcatalogservice }}
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ $ns.backend }}
  name: recommendation-route
  labels:
    app: recommendationservice
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gw.name }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/recommendations
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /recommendations
      backendRefs:
        - group: ""
          kind: Service
          name: recommendationservice
          port: {{ $ports.recommendationservice }}
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ $ns.backend }}
  name: shipping-route
  labels:
    app: shippingservice
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gw.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/shipping
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - group: ""
          kind: Service
          name: shippingservice
          port: {{ $ports.shippingservice }}
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: {{ $ns.backend }}
  name: assistant-route
  labels:
    app: assistantservice
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gw.name }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /api/assistant/chat
      backendRefs:
        - group: ""
          kind: Service
          name: assistantservice
          port: {{ $ports.assistantservice }}
          weight: 1
