apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    # Wave 0
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hipstershop

  source:
    repoURL: https://github.com/HipsterShopp/hipstershop-helm-charts
    targetRevision: main
    path: hipstershop-infra/mongodb
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: hipster-database  

  syncPolicy:
    automated:
      selfHeal: true
      prune: false   
    syncOptions:
      - CreateNamespace=false   
      - ServerSideApply=true
      - RespectIgnoreDifferences=true   


  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: mongodb
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/revisionHistoryLimit
        - /spec/updateStrategy
