# ─────────────────────────────────────────────────────────────
#  cartservice — dev overrides
# ─────────────────────────────────────────────────────────────
global:
  replicas:
    cartservice: 1
  resources:
    standard:
      requests: { cpu: 50m, memory: 64Mi }
      limits:   { cpu: 100m, memory: 128Mi }
  images:
    cartservice: "yampss/hipstershop-cartservice:develop-fc380064"
