# ─────────────────────────────────────────────────────────────
#  checkoutservice — prod overrides
# ─────────────────────────────────────────────────────────────
global:
  replicas:
    checkoutservice: 1
  resources:
    standard:
      requests: { cpu: 100m, memory: 128Mi }
      limits:   { cpu: 200m, memory: 256Mi }
  images:
    checkoutservice: "yampss/hipstershop-checkoutservice:latest"
